tasks:
  - name: aws-cli
    before:
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo apt update
      sudo apt install unzip -y
      sudo ./aws/install
      aws --version

