AWSTemplateFormatVersion: "2010-09-09"
Description: A Simple SQS queue
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    # Properties:
      # QueueName: "StandardQueue"
      # docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
      # FifoQueue: true
