#!/usr/bin/env bash
# chmod u+x deploy
# ./deploy
# docs.aws.amazon.com/autoscaling/plans/userguide/gs-select-application.html

echo "== deploy ec2"

STACK_NAME="aws-ec2-basic"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy/index.html
aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region ca-central-1 \
--stack-name $STACK_NAME