#!/usr/bin/env bash

# # VPC IGW  SUBNET RT

# Check if the argument is not provided
if [ -z "$1" ]; then
  echo "Argument not provided."
  exit 1
else
  export VPC_ID="$1"
fi

if [ -z "$2" ]; then
  echo "Argument not provided."
else
  export IGW_ID="$2"
fi

if [ -z "$3" ]; then
  echo "Argument not provided."
else
  export SUBNET_ID="$3"
fi

if [ -z "$4" ]; then
  echo "Argument not provided."
else
  export ASSOC_ID="$4"
fi

if [ -z "$5" ]; then
  echo "Argument not provided."
else
  export RT_ID="$5"
fi


# delete vpc
aws ec2 delete-vpc --vpc-id $VPC_ID

# sur le console 
# ./delete_vpc vpc-08a315da715e9cd14
# vpc-08a315da715e9cd14 est le id du vpc

# detach the IGW
aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# delete the IGW

# dissaociate subnet

$ASSOC_ID=$(aws ec2 describe-route-tables \
--route-table-ids $RT_ID \
--filters "Name=association.subnet-id,Values=$SUBNET_ID" \
--query "RouteTables[].Associations[?SubnetId=='$SUBNET_ID'].RouteTableAssociationId[]" \
--output text)

echo "ASSOC_ID: $ASSOC_ID"

aws ec2 disassociate-route-table --association-id $ASSOC_ID

# delete subnet
aws ec2 delete-subnet --subnet-id $SUBNET_ID

# delete route table
aws ec2 delete-route-table --route-table-id $RT_ID

# delete vpc
aws ec2 delete-vpc --vpc-id $VPC_ID


