#!/usr/bin/env bash

# Check for bucket name
# ./S3/bash-scripts/create-bukets my_new_buket
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUKET_NAME = $1

#echo "aws s3api create-bucket --bucket BUKET_NAME"
#aws s3api create-bucket --bucket-name --region us-east-1
# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=ca-central-1" \
--query Location \
--output text