#!/usr/bin/env bash

 

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/index.html
echo "== deploy s3 bucket via CFN"

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region ca-central-1 \
--stack-name $STACK_NAME